name: Shell Check

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: warning
          additional_files: wg-keychain-export

  shfmt:
    name: shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check shell formatting
        uses: mvdan/sh@v3
        with:
          shfmt: -d -i 4 -bn -ci
          path: wg-keychain-export
